{{ if eq (lower .Values.scheduler.type) "daemonset" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: topolvm-scheduler
  labels:
  {{- include "topolvm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: topolvm-scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: topolvm-scheduler
    spec:
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      serviceAccountName: topolvm-scheduler
      terminationGracePeriodSeconds: {{ .Values.scheduler.terminationGracePeriodSeconds }}
      containers:
        - name: topolvm-scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /topolvm-scheduler
            - --config=/etc/topolvm/scheduler-options.yaml
          livenessProbe:
            httpGet:
              host: {{ .Values.scheduler.options.listen.host }}
              port: {{ .Values.scheduler.options.listen.port }}
              path: /status
          volumeMounts:
            - mountPath: /etc/topolvm
              name: scheduler-options
          resources:
{{ toYaml .Values.scheduler.resources | indent 12 }}
      hostNetwork: true
      {{- with .Values.scheduler.daemonset.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.scheduler.daemonset.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
        - name: scheduler-options
          configMap:
            name: scheduler-options
{{ end }}