{{ if .Values.storageclass.create }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: topolvm-provisioner
  {{- with .Values.storageclass.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
  {{- include "topolvm.labels" . | nindent 4 }}
provisioner: topolvm.cybozu.com
parameters:
  "csi.storage.k8s.io/fstype": {{ .Values.storageclass.fstype | quote }}
volumeBindingMode: {{ .Values.storageclass.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storageclass.allowVolumeExpansion }}
{{ end }}